import copy
black = 1
gray = 2
red = 3
green = 4
blue = 5
yellow = 6
orange = 7
cyan = 8
violett = 9

def scenario(sim):
    sim.add_tile(0.0, 2.0)
    sim.add_tile(3.0, 2.0)
    sim.add_tile(0.5, 3.0)
    sim.add_tile(1.5, 3.0)
    sim.add_tile(2.5, 3.0)
    sim.add_tile(3.5, 1.0)
    sim.add_tile(3.0, 0.0)
    sim.add_tile(0.0, 0.0)
    sim.add_tile(-0.5, 1.0)
    sim.add_particle(-0.5, -1.0, color=red)
    sim.add_particle(-1.0, 0.0, color=red)
    sim.add_particle(0.5, -1.0, color=red)
    sim.add_particle(-1.5, 1.0, color=red)
    sim.add_particle(1.0, 0.0, color=red)
    sim.add_particle(-1.0, 2.0, color=red)
    sim.add_particle(0.5, 1.0, color=red)
    sim.add_particle(-0.5, 3.0, color=red)
    sim.add_particle(1.0, 2.0, color=red)
    sim.add_particle(0.0, 4.0, color=red)
    sim.add_particle(2.0, 2.0, color=red)
    sim.add_particle(1.0, 4.0, color=red)
    sim.add_particle(2.5, 1.0, color=red)
    sim.add_particle(2.0, 4.0, color=red)
    sim.add_particle(2.0, 0.0, color=red)
    sim.add_particle(3.0, 4.0, color=red)
    sim.add_particle(2.5, -1.0, color=red)
    sim.add_particle(3.5, 3.0, color=red)
    sim.add_particle(3.5, -1.0, color=red)
    sim.add_particle(4.0, 0.0, color=red)
    sim.add_particle(4.0, 2.0, color=red)
    sim.add_particle(4.5, 1.0, color=red)
    sim.add_particle(-1.5, 3.0, color=blue)
    sim.add_particle(-1.0, 4.0, color=blue)
    sim.add_particle(-2.0, 2.0, color=blue)
    sim.add_particle(-0.5, 5.0, color=blue)
    sim.add_particle(-2.5, 1.0, color=blue)
    sim.add_particle(0.5, 5.0, color=blue)
    sim.add_particle(-2.0, 0.0, color=blue)
    sim.add_particle(1.5, 5.0, color=blue)
    sim.add_particle(-1.5, -1.0, color=blue)
    sim.add_particle(2.5, 5.0, color=blue)
    sim.add_particle(-1.0, -2.0, color=blue)
    sim.add_particle(0.0, -2.0, color=blue)
    sim.add_particle(3.5, 5.0, color=blue)
    sim.add_particle(1.0, -2.0, color=blue)
    sim.add_particle(1.5, -1.0, color=blue)
    sim.add_particle(4.0, 4.0, color=blue)
    sim.add_particle(2.0, -2.0, color=blue)
    sim.add_particle(3.0, -2.0, color=blue)
    sim.add_particle(4.5, 3.0, color=blue)
    sim.add_particle(4.0, -2.0, color=blue)
    sim.add_particle(4.5, -1.0, color=blue)
    sim.add_particle(5.0, 2.0, color=blue)
    sim.add_particle(5.0, 0.0, color=blue)
    sim.add_particle(5.5, 1.0, color=blue)
    sim.add_particle(6.5, 1.0)

    sim.add_location(1.5, 1.0)
