def doubleline20(sim):
    sim.add_particle(-5, 0)
    sim.add_particle(-4, 0)
    sim.add_particle(-3, 0)
    sim.add_particle(-2, 0)
    sim.add_particle(-1, 0)
    sim.add_particle(0, 0)
    sim.add_particle(1, 0)
    sim.add_particle(2, 0)
    sim.add_particle(3, 0)
    sim.add_particle(4, 0)
    sim.add_particle(-5.5, 1)
    sim.add_particle(-4.5, 1)
    sim.add_particle(-3.5, 1)
    sim.add_particle(-2.5, 1)
    sim.add_particle(-1.5, 1)
    sim.add_particle(-0.5, 1)
    sim.add_particle(0.5, 1)
    sim.add_particle(1.5, 1)
    sim.add_particle(2.5, 1)
    sim.add_particle(3.5, 1)


def around37(sim):
    sim.add_particle(3, 0)
    sim.add_particle(1, 0)
    sim.add_particle(-1, 0)
    sim.add_particle(-0.5, 1)
    sim.add_particle(0.5, 1)
    sim.add_particle(-0.5, -1)
    sim.add_particle(0.5, -1)
    sim.add_particle(2, 0)
    sim.add_particle(-2, 0)
    sim.add_particle(-1.5, 1)
    sim.add_particle(1.5, 1)
    sim.add_particle(0, 2)
    sim.add_particle(-1, 2)
    sim.add_particle(1, 2)
    sim.add_particle(-1.5, -1)
    sim.add_particle(1.5, -1)
    sim.add_particle(0, -2)
    sim.add_particle(-1, -2)
    sim.add_particle(1, -2)
    sim.add_particle(-3, 0)
    sim.add_particle(-2.5, 1)
    sim.add_particle(2.5, 1)
    sim.add_particle(-2, 2)
    sim.add_particle(2, 2)
    sim.add_particle(-1.5, 3)
    sim.add_particle(1.5, 3)
    sim.add_particle(-0.5, 3)
    sim.add_particle(0.5, 3)
    sim.add_particle(-2.5, -1)
    sim.add_particle(2.5, -1)
    sim.add_particle(-2, -2)
    sim.add_particle(2, -2)
    sim.add_particle(-1.5, -3)
    sim.add_particle(1.5, -3)
    sim.add_particle(-0.5, -3)
    sim.add_particle(0.5, -3)
    sim.add_particle(0, 0)

def star50(sim):
    sim.add_particle(3,0)
    sim.add_particle(2,0)
    sim.add_particle(1,0)
    sim.add_particle(0,0)
    sim.add_particle(-1,0)
    sim.add_particle(-2,0)
    sim.add_particle(-3,0)
    sim.add_particle(-4,0)
    sim.add_particle(-5,0)
    sim.add_particle(-6,0)
    sim.add_particle(-7,0)
    sim.add_particle(-8,0)
    sim.add_particle(-9,0)
    sim.add_particle(-10,0)

    sim.add_particle(-2.5, 1)
    sim.add_particle(-2.5, -1)
    sim.add_particle(-3.5, 1)
    sim.add_particle(-3.5, -1)

    sim.add_particle(-2, 2)
    sim.add_particle(-2, -2)
    sim.add_particle(-4, 2)
    sim.add_particle(-4, -2)

    sim.add_particle(-1.5, 3)
    sim.add_particle(-1.5, -3)
    sim.add_particle(-4.5, 3)
    sim.add_particle(-4.5, -3)

    sim.add_particle(-1, 4)
    sim.add_particle(-1, -4)
    sim.add_particle(-5, 4)
    sim.add_particle(-5, -4)

    sim.add_particle(-0.5, 5)
    sim.add_particle(-0.5, -5)
    sim.add_particle(-5.5, 5)
    sim.add_particle(-5.5, -5)

    sim.add_particle(0, 6)
    sim.add_particle(0, -6)
    sim.add_particle(-6, 6)
    sim.add_particle(-6, -6)

    #38
    sim.add_particle(0.5, 7)
    sim.add_particle(0.5, -7)
    sim.add_particle(-6.5, 7)
    sim.add_particle(-6.5, -7)

    sim.add_particle(1, 8)
    sim.add_particle(1, -8)
    sim.add_particle(-7, 8)
    sim.add_particle(-7, -8)

    sim.add_particle(1.5, 9)
    sim.add_particle(1.5, -9)
    sim.add_particle(-7.5, 9)
    sim.add_particle(-7.5, -9)

    sim.add_particle(2, 10)
    sim.add_particle(2, -10)
    sim.add_particle(-8, 10)
    sim.add_particle(-8, -10)

def block100(sim):
    for i in range(0,10):
        for j in range(0,20):
            if j%2 == 0:
                sim.add_particle(i-5,j)
            else:
                sim.add_particle(i - 5.5, j)