from scenario.scenario_std_lib import *

max_size_particle = 200


def scenario(sim):

    sim.add_tile(0.0, 0.0)
    sim.add_tile(-0.5, 1.0)
    sim.add_tile(-1.0, 2.0)
    sim.add_tile(1.0, 6.0)
    sim.add_tile(2.0, 6.0)
    sim.add_tile(3.0, 6.0)
    sim.add_tile(4.0, 6.0)
    sim.add_tile(5.0, 6.0)
    sim.add_tile(5.5, 5.0)
    sim.add_tile(6.0, 4.0)
    sim.add_tile(6.5, 3.0)
    sim.add_tile(6.0, 2.0)
    sim.add_tile(5.5, 1.0)
    sim.add_tile(5.0, 0.0)
    sim.add_tile(-1.5, 3.0)
    sim.add_tile(-1.0, 4.0)
    sim.add_tile(-0.5, 5.0)
    sim.add_tile(-0.0, 6.0)

    #create_particle_in_line(sim, max_size_particle)
    generating_random_spraded_particles(sim, max_size_particle)
    # for i in range(0, max):
    #     x = random.randrange(-sim.get_sim_x_size(), sim.get_sim_x_size())
    #     y = random.randrange(-sim.get_sim_y_size(), sim.get_sim_y_size())
    #     if y % 2 == 1:
    #         x = x + 0.5
    #     if (x, y) not in sim.tile_map_coords:
    #         sim.add_particle(x, y)
    #     else:
    #         print(" x and y ", (x, y))
    # print("Max Size of created Particle", len(sim.particles))
    # sim.add_particle(1.0, 0.0, color=red)
    # sim.add_particle(0.5, -1.0, color=red)
    # sim.add_particle(0.5, 1.0, color=red)
    # sim.add_particle(-0.5, -1.0, color=red)
    # sim.add_particle(0.0, 2.0, color=red)
    # sim.add_particle(-1.0, 0.0, color=red)
    # sim.add_particle(-0.5, 3.0, color=red)
    # sim.add_particle(-1.5, 1.0, color=red)
    # sim.add_particle(0.0, 4.0, color=red)
    # sim.add_particle(-2.0, 2.0, color=red)
    # sim.add_particle(0.5, 5.0, color=red)
    # sim.add_particle(-2.5, 3.0, color=red)
    # sim.add_particle(1.5, 5.0, color=red)
    # sim.add_particle(-2.0, 4.0, color=red)
    # sim.add_particle(2.5, 5.0, color=red)
    # sim.add_particle(-1.5, 5.0, color=red)
    # sim.add_particle(3.5, 5.0, color=red)
    # sim.add_particle(-1.0, 6.0, color=red)
    # sim.add_particle(4.5, 5.0, color=red)
    # sim.add_particle(-0.5, 7.0, color=red)
    # sim.add_particle(5.0, 4.0, color=red)
    # sim.add_particle(0.5, 7.0, color=red)
    # sim.add_particle(5.5, 3.0, color=red)
    # sim.add_particle(1.5, 7.0, color=red)
    # sim.add_particle(5.0, 2.0, color=red)
    # sim.add_particle(2.5, 7.0, color=red)
    # sim.add_particle(4.5, 1.0, color=red)
    # sim.add_particle(3.5, 7.0, color=red)
    # sim.add_particle(4.0, 0.0, color=red)
    # sim.add_particle(4.5, 7.0, color=red)
    # sim.add_particle(4.5, -1.0, color=red)
    # sim.add_particle(5.5, 7.0, color=red)
    # sim.add_particle(5.5, -1.0, color=red)
    # sim.add_particle(6.0, 6.0, color=red)
    # sim.add_particle(6.0, 0.0, color=red)
    # sim.add_particle(6.5, 5.0, color=red)
    # sim.add_particle(6.5, 1.0, color=red)
    # sim.add_particle(7.0, 4.0, color=red)
    # sim.add_particle(7.0, 2.0, color=red)
    # sim.add_particle(7.5, 3.0, color=red)
    # sim.add_particle(-1.0, -2.0, color=red)
    # sim.add_particle(-1.5, -1.0, color=red)
    # sim.add_particle(0.0, -2.0, color=red)
    # sim.add_particle(-2.0, 0.0, color=red)
    # sim.add_particle(1.0, -2.0, color=red)
    # sim.add_particle(-2.5, 1.0, color=red)
    # sim.add_particle(1.5, -1.0, color=red)
    # sim.add_particle(-3.0, 2.0, color=red)
    # sim.add_particle(2.0, 0.0, color=red)
    # sim.add_particle(-3.5, 3.0, color=red)
    # sim.add_particle(1.5, 1.0, color=red)
    # sim.add_particle(-3.0, 4.0, color=red)
    # sim.add_particle(1.0, 2.0, color=red)
    # sim.add_particle(-2.5, 5.0, color=red)
    # sim.add_particle(0.5, 3.0, color=red)
    # sim.add_particle(-2.0, 6.0, color=red)
    # sim.add_particle(1.0, 4.0, color=red)
    # sim.add_particle(-1.5, 7.0, color=red)
    # sim.add_particle(2.0, 4.0, color=red)
    # sim.add_particle(-1.0, 8.0, color=red)
    # sim.add_particle(3.0, 4.0, color=red)
    # sim.add_particle(0.0, 8.0, color=red)
    # sim.add_particle(4.0, 4.0, color=red)
    # sim.add_particle(1.0, 8.0, color=red)
    # sim.add_particle(4.5, 3.0, color=red)
    # sim.add_particle(2.0, 8.0, color=red)
    # sim.add_particle(4.0, 2.0, color=red)
    # sim.add_particle(3.0, 8.0, color=red)
    # sim.add_particle(3.5, 1.0, color=red)
    # sim.add_particle(4.0, 8.0, color=red)
    # sim.add_particle(3.0, 0.0, color=red)
    # sim.add_particle(5.0, 8.0, color=red)
    # sim.add_particle(3.5, -1.0, color=red)
    # sim.add_particle(6.0, 8.0, color=red)
    # sim.add_particle(4.0, -2.0, color=red)
    # sim.add_particle(6.5, 7.0, color=red)
    # sim.add_particle(5.0, -2.0, color=red)
    # sim.add_particle(7.0, 6.0, color=red)
    # sim.add_particle(6.0, -2.0, color=red)
    # sim.add_particle(7.5, 5.0, color=red)
    # sim.add_particle(6.5, -1.0, color=red)
    # sim.add_particle(7.0, 0.0, color=red)
    # sim.add_particle(8.0, 4.0, color=red)
    # sim.add_particle(7.5, 1.0, color=red)
    # sim.add_particle(8.0, 2.0, color=red)
    # sim.add_particle(8.5, 3.0, color=red)
    # sim.add_particle(-3.5, 5.0, color=blue)
    # sim.add_particle(-3.0, 6.0, color=blue)
    # sim.add_particle(-4.0, 4.0, color=blue)
    # sim.add_particle(-2.5, 7.0, color=blue)
    # sim.add_particle(-4.5, 3.0, color=blue)
    # sim.add_particle(-2.0, 8.0, color=blue)
    # sim.add_particle(-4.0, 2.0, color=blue)
    # sim.add_particle(-1.5, 9.0, color=blue)
    # sim.add_particle(-3.5, 1.0, color=blue)
    # sim.add_particle(-0.5, 9.0, color=blue)
    # sim.add_particle(-3.0, 0.0, color=blue)
    # sim.add_particle(0.5, 9.0, color=blue)
    # sim.add_particle(-2.5, -1.0, color=blue)
    # sim.add_particle(1.5, 9.0, color=blue)
    # sim.add_particle(-2.0, -2.0, color=blue)
    # sim.add_particle(2.5, 9.0, color=blue)
    # sim.add_particle(-1.5, -3.0, color=blue)
    # sim.add_particle(3.5, 9.0, color=blue)
    # sim.add_particle(-0.5, -3.0, color=blue)
    # sim.add_particle(4.5, 9.0, color=blue)
    # sim.add_particle(0.5, -3.0, color=blue)
    # sim.add_particle(1.5, -3.0, color=blue)
    # sim.add_particle(5.5, 9.0, color=blue)
    # sim.add_particle(2.0, -2.0, color=blue)
    # sim.add_particle(2.5, -1.0, color=blue)
    # sim.add_particle(3.0, -2.0, color=blue)
    # sim.add_particle(6.5, 9.0, color=blue)
    # sim.add_particle(3.5, -3.0, color=blue)
    # sim.add_particle(4.5, -3.0, color=blue)
    # sim.add_particle(7.0, 8.0, color=blue)
    # sim.add_particle(5.5, -3.0, color=blue)
    # sim.add_particle(6.5, -3.0, color=blue)
    # sim.add_particle(7.5, 7.0, color=blue)
    # sim.add_particle(7.0, -2.0, color=blue)
    # sim.add_particle(7.5, -1.0, color=blue)
    # sim.add_particle(8.0, 6.0, color=blue)
    # sim.add_particle(8.0, 0.0, color=blue)
    # sim.add_particle(8.5, 5.0, color=blue)
    # sim.add_particle(8.5, 1.0, color=blue)
    # sim.add_particle(9.0, 2.0, color=blue)
    # sim.add_particle(9.0, 4.0, color=blue)
    # sim.add_particle(9.5, 3.0, color=blue)
    # sim.add_particle(10.5, 3.0)
    # sim.add_particle(9.5, 5.0)
    # sim.add_particle(12.5, 3.0)
    # sim.add_particle(13.5, 3.0)
    # sim.add_particle(14.5, 3.0)
    # sim.add_particle(15.5, 3.0)
    #
    # sim.add_marker(1.5, 3.0)
    # sim.add_marker(2.5, 3.0)
    # sim.add_marker(3.5, 3.0)
    # sim.add_marker(3.0, 2.0)
    # sim.add_marker(2.0, 2.0)
    # sim.add_marker(2.5, 1.0)
